### ISSUE TITLE
Знайти готель поблизу центру містас 

### ISSUE THREAD

**Issue by HoldenLem** [cassiopeiav/hello-world228#5]
Ось приклад готелю[
[
![image](https://user-images.githubusercontent.com/38036806/38865729-5f760778-4247-11e8-9637-686b4c59027a.png) 
](![image](https://user-images.githubusercontent.com/38036806/38865706-515933f4-4247-11e8-9baa-369907059d9f.png))
]
[
![image](https://user-images.githubusercontent.com/38036806/38865772-7b299de0-4247-11e8-879a-b3101b1158f2.png)
]
[
![image](https://user-images.githubusercontent.com/38036806/38865786-895fe64e-4247-11e8-809d-03bf163a6a6d.png) 
]

**Comment by cassiopeiav** [comment]
Я обираю готель номер 3
