### ISSUE TITLE
Розробити програму екскурсії

### ISSUE THREAD

**Issue by cassiopeiav** [cassiopeiav/hello-world228#6]
Є дві короткі олглядові екскурсії по вигідній ціні, ми зможемо ознайомитись,а потім продовжити тусити самі

**Comment by cassiopeiav** [comment]
Оглядова екскурсія з «Секретами Барселони» можлива у двох варіантах:
1. Варіант «Експрес»
Тривалість 3,5 – 4 години.
Mаршрут:

Готичний квартал, Кафедральний собор та Королівський палац Барселони;
Бульвар Рамблас, площа Каталонії та Старий Порт з монументом Христофору Колумбу;
Найголовніші твори архітектора Антоні Ґауді: дома Батльо та Міла на бульварі Ґрасії, славетний храм Святого Сімейства (Саґрада Фамілія);
пагорб Монтжуїк, Національний Палац і площа Іспанії;
Парк Цитаделі та Тріумфальна Арка.
Oглядова екскурсія Барселоною
Саґрада Фамілія

2. Варіант «Ексклюзив»
Тривалість — 5 годин
Екскурсію складає увесь маршрут варіанта «Експрес», плюс:

Більш детальна прогулянка Готичним кварталом та огляд з середини Кафедрального собору;
Шпиталь Св. Павла — шедевр архітектури доби модерн;
Парк Ґуель — ще один шедевр архітектора Ґауді.

**Comment by HoldenLem** [comment]
Більше  до вподоби 2 варіант, займає більше часу та цікавіше

**Comment by cassiopeiav** [comment]
Окей
